-- ============================================================
--  GARMENT STORE MANAGEMENT SYSTEM — PostgreSQL (Neon) Schema
-- ============================================================

-- Note: Neon provides the database. Connect to your Neon DB, then run this schema.

-- ─────────────────────────────────────────────
--  ENUM TYPES
-- ─────────────────────────────────────────────
CREATE TYPE cloth_type AS ENUM ('Shirt','Pant','Dress','Saree','Kurta','Jacket','Skirt','Suit');
CREATE TYPE fabric_type AS ENUM ('Cotton','Silk','Wool','Polyester','Linen','Denim','Rayon');
CREATE TYPE size_type AS ENUM ('XS','S','M','L','XL','XXL');
CREATE TYPE stock_status AS ENUM ('In-Stock','Sold');
CREATE TYPE complaint_status AS ENUM ('Open','In-Progress','Resolved');

-- ─────────────────────────────────────────────
--  1. BRANCHES
-- ─────────────────────────────────────────────
CREATE TABLE branches (
    branch_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(100) NOT NULL UNIQUE,
    contact_no  VARCHAR(15)  NOT NULL,
    manager     VARCHAR(100) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────
--  2. EMPLOYEES
-- ─────────────────────────────────────────────
CREATE TABLE employees (
    emp_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    address     TEXT         NOT NULL,
    designation VARCHAR(80)  NOT NULL,
    contact_no  VARCHAR(15)  NOT NULL,
    branch_id   INT          NOT NULL,
    salary      DECIMAL(10,2) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE RESTRICT
);

-- ─────────────────────────────────────────────
--  3. CUSTOMERS
-- ─────────────────────────────────────────────
CREATE TABLE customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    address     TEXT         NOT NULL,
    contact_no  VARCHAR(15)  NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────
--  4. DESIGNERS
-- ─────────────────────────────────────────────
CREATE TABLE designers (
    designer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    address     TEXT         NOT NULL,
    contact_no  VARCHAR(15)  NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ─────────────────────────────────────────────
--  5. CLOTHES
-- ─────────────────────────────────────────────
CREATE TABLE clothes (
    cloth_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        cloth_type NOT NULL,
    fabric      fabric_type NOT NULL,
    colour      VARCHAR(50)  NOT NULL,
    size        size_type NOT NULL,
    price       DECIMAL(10,2) NOT NULL,
    mfd         DATE          NOT NULL,
    sold_date   DATE          DEFAULT NULL,
    status      stock_status NOT NULL DEFAULT 'In-Stock',
    designer_id INT           DEFAULT NULL,
    branch_id   INT           NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (designer_id) REFERENCES designers(designer_id) ON DELETE SET NULL,
    FOREIGN KEY (branch_id)   REFERENCES branches(branch_id)   ON DELETE RESTRICT
);

COMMENT ON COLUMN clothes.mfd IS 'Manufacturing date';

-- ─────────────────────────────────────────────
--  6. ORDERS  (cart → checkout)
-- ─────────────────────────────────────────────
CREATE TABLE orders (
    order_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT           NOT NULL,
    cloth_id    INT           NOT NULL,
    quantity    INT           NOT NULL DEFAULT 1,
    total_price DECIMAL(10,2) NOT NULL,
    order_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE,
    FOREIGN KEY (cloth_id)    REFERENCES clothes(cloth_id)      ON DELETE RESTRICT
);

-- ─────────────────────────────────────────────
--  7. COMPLAINTS
-- ─────────────────────────────────────────────
CREATE TABLE complaints (
    complaint_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      INT           NOT NULL,
    description      TEXT          NOT NULL,
    complaint_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    solution         TEXT          DEFAULT NULL,
    status           complaint_status DEFAULT 'Open',
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE
);

-- ─────────────────────────────────────────────
--  SEED DATA — Branches
-- ─────────────────────────────────────────────
INSERT INTO branches (branch_name, contact_no, manager) VALUES
('Main Street Branch',   '9876543210', 'Arjun Mehta'),
('South Delhi Branch',   '9123456780', 'Priya Sharma'),
('Connaught Place Branch','9012345678','Rohit Verma');

-- SEED — Designers
INSERT INTO designers (name, address, contact_no) VALUES
('Anita Dongre',   'Mumbai, MH',   '9900112233'),
('Manish Malhotra','Delhi, DL',    '9800223344'),
('Ritu Kumar',     'Kolkata, WB',  '9700334455');

-- SEED — Employees
INSERT INTO employees (name, address, designation, contact_no, branch_id, salary) VALUES
('Karan Singh',    'Pitampura, Delhi', 'Store Manager',  '9111222333', 1, 55000),
('Sunita Rao',     'Rohini, Delhi',    'Sales Associate','9222333444', 1, 28000),
('Mohan Das',      'Lajpat Nagar',     'Accountant',     '9333444555', 2, 35000),
('Meena Kapoor',   'CP, Delhi',        'Store Manager',  '9444555666', 3, 52000);

-- SEED — Clothes
INSERT INTO clothes (type, fabric, colour, size, price, mfd, status, designer_id, branch_id) VALUES
('Shirt',  'Cotton',    'Sky Blue', 'M',   899.00,  '2024-01-15', 'In-Stock', 1, 1),
('Saree',  'Silk',      'Red',      'L',   4500.00, '2023-11-10', 'In-Stock', 2, 1),
('Kurta',  'Cotton',    'White',    'XL',  1200.00, '2024-02-20', 'In-Stock', 3, 2),
('Dress',  'Polyester', 'Black',    'S',   2200.00, '2024-03-05', 'In-Stock', 1, 2),
('Pant',   'Denim',     'Navy',     'M',   1500.00, '2024-01-25', 'In-Stock', NULL, 3),
('Jacket', 'Wool',      'Charcoal', 'L',   3800.00, '2023-12-01', 'Sold',     2, 1),
('Suit',   'Wool',      'Grey',     'XL',  8500.00, '2024-02-10', 'In-Stock', 2, 3),
('Skirt',  'Linen',     'Beige',    'S',   1100.00, '2024-03-01', 'In-Stock', 3, 2);

-- SEED — Customers
INSERT INTO customers (name, address, contact_no) VALUES
('Rahul Gupta',   'Pitampura, Delhi', '9555111222'),
('Anjali Verma',  'Dwarka, Delhi',    '9444222333'),
('Sameer Khan',   'Noida, UP',        '9333111444');

-- SEED — Complaints
INSERT INTO complaints (customer_id, description) VALUES
(1, 'The shirt fabric started fading after first wash.'),
(2, 'Received wrong size. Ordered M but got XL.'),
(3, 'Zipper on jacket is broken.');
